#!/bin/bash

# Script to comprehensively replace remaining Chinese text in server/index.js

FILE="server/index.js"

echo "Performing comprehensive replacement of Chinese text in $FILE..."

# Style labels  
sed -i '' 's/简约现代风格/Minimalist Modern Style/g' "$FILE"
sed -i '' 's/新拟物化 (Neumorphism) 风格/Neumorphism Style/g' "$FILE"
sed -i '' 's/玻璃拟态 (Glassmorphism) 风格/Glassmorphism Style/g' "$FILE"
sed -i '' 's/赛博朋克风格/Cyberpunk Style/g' "$FILE"
sed -i '' 's/复古风格/Retro Style/g' "$FILE"
sed -i '' 's/Material Design 风格/Material Design Style/g' "$FILE"
sed -i '' 's/Ant Design 设计风格/Ant Design Style/g' "$FILE"
sed -i '' 's/简约现代/Minimalist Modern/g' "$FILE"
sed -i '' 's/新拟物化/Neumorphism/g' "$FILE"
sed -i '' 's/玻璃拟态/Glassmorphism/g' "$FILE"
sed -i '' 's/赛博朋克/Cyberpunk/g' "$FILE"
sed -i '' 's/复古/Retro/g' "$FILE"

sed -i '' 's/纯 HTML + CSS + JavaScript/Pure HTML + CSS + JavaScript/g' "$FILE"
sed -i '' 's/不需要构建工具/requires no build tools/g' "$FILE"
sed -i '' 's/不使用任何第三方UI库，使用原生手写样式/No third-party UI library, using native styles/g' "$FILE"
sed -i '' 's/使用原生纯 CSS/Using native pure CSS/g' "$FILE"
sed -i '' 's/使用 SCSS 预处理样式/Using SCSS preprocessor/g' "$FILE"
sed -i '' 's/使用 LESS 预处理样式/Using LESS preprocessor/g' "$FILE"
sed -i '' 's/使用 Tailwind CSS 进行样式开发/Using Tailwind CSS/g' "$FILE"

# Component type label
sed -i '' 's/需要添加完整的交互事件处理/Requires complete interaction event handling/g' "$FILE"
sed -i '' 's/不需要复杂交互/No complex interactions needed/g' "$FILE"
sed -i '' 's/请生成合理的默认 Mock 数据，方便直接预览，把 Mock 数据放在代码顶部方便编辑/Generate reasonable default mock data for direct preview, place mock data at top of code for easy editing/g' "$FILE"
sed -i '' 's/不需要 Mock 数据/No mock data needed/g' "$FILE"
sed -i '' 's/额外需求/Additional requirements/g' "$FILE"

# Build requirements section comments
sed -i '' 's/构建需求分析部分（如果有）/Build requirements analysis section (if any)/g' "$FILE"
sed -i '' 's/详细需求分析（重要参考！）/Detailed Requirements Analysis (Important Reference!)/g' "$FILE"
sed -i '' 's/功能列表/Feature List/g' "$FILE"
sed -i '' 's/技术要点/Technical Notes/g' "$FILE"
sed -i '' 's/组件结构参考/Component Structure Reference/g' "$FILE"
sed -i '' 's/布局原型参考/Layout Prototype Reference/g' "$FILE"
sed -i '' 's/请严格按照以上需求分析生成代码，确保实现所有功能和符合技术规范！/Please strictly follow the above requirements analysis to generate code, ensuring all features are implemented and technical specifications are met!/g' "$FILE"

# Note: The buildPrompt function contains Chinese templates for AI
# These are DEPRECATED since AI generation is now handled by Pages Functions
# Adding deprecation comment
sed -i '' 's/function buildPrompt(params)/\/\/ DEPRECATED: This function is no longer used (AI generation moved to Pages Functions)\nfunction buildPrompt(params)/g' "$FILE"

# Refinement prompt function  
sed -i '' 's/你是一个资深前端架构师和产品经理。请根据用户的组件需求，生成详细的需求分析文档。/You are a senior frontend architect and product manager. Please generate detailed requirements analysis documentation based on user component requirements./g' "$FILE"
sed -i '' 's/用户原始需求/User Original Requirements/g' "$FILE"
sed -i '' 's/未指定/Not specified/g' "$FILE"
sed -i '' 's/技术栈/Technology Stack/g' "$FILE"
sed -i '' 's/设计风格/Design Style/g' "$FILE"
sed -i '' 's/原生手写（不使用第三方库）/Native (no third-party library)/g' "$FILE"
sed -i '' 's/需要 Mock 数据/Needs Mock Data/g' "$FILE"
sed -i '' 's/需要交互/Needs Interactions/g' "$FILE"
sed -i '' 's/原始描述/Original Description/g' "$FILE"
sed -i '' 's/任务要求/Task Requirements/g' "$FILE"
sed -i '' 's/请严格按照以下 JSON 格式输出需求分析结果（不要输出其他内容）/Please output requirements analysis results strictly in the following JSON format (do not output other content)/g' "$FILE"
sed -i '' 's/要求说明/Requirements Explanation/g' "$FILE"
sed -i '' 's/将用户简短的描述扩写为专业的产品需求文档风格/Expand user'\''s brief description into professional product requirements document style/g' "$FILE"
sed -i '' 's/使用 Mermaid graph TD 语法绘制组件层次结构图/Use Mermaid graph TD syntax to draw component hierarchy diagram/g' "$FILE"
sed -i '' 's/列出/ List/g' "$FILE"
sed -i '' 's/个核心功能点/ core feature points/g' "$FILE"
sed -i '' 's/使用 Mermaid block-beta 或 flowchart 语法绘制组件布局原型图/Use Mermaid block-beta or flowchart syntax to draw component layout prototype/g' "$FILE"
sed -i '' 's/个技术实现要点（如状态管理、性能优化、可访问性等）/ technical implementation points (e.g., state management, performance optimization, accessibility)/g' "$FILE"
sed -i '' 's/组件结构图示例/Component Structure Diagram Example/g' "$FILE"
sed -i '' 's/布局原型图示例/Layout Prototype Diagram Example/g' "$FILE"
sed -i '' 's/Please直接输出 JSON 格式的结果,不要包含任何解释或其他文字。/Please directly output the JSON format result, do not include any explanation or other text./g' "$FILE"
sed -i '' 's/商品卡片/Product Card/g' "$FILE"
sed -i '' 's/商品图片/Product Image/g' "$FILE"
sed -i '' 's/内容区域/Content Area/g' "$FILE"
sed -i '' 's/标签区域/Badges Area/g' "$FILE"
sed -i '' 's/商品标题/Product Title/g' "$FILE"
sed -i '' 's/价格/Price/g' "$FILE"
sed -i '' 's/操作按钮区/Action Buttons Area/g' "$FILE"

# Expand prompt function
sed -i '' 's/你是一个专业的前端产品需求分析师。请根据用户提供的组件简要描述，进行详细扩写。/You are a professional frontend product requirements analyst. Please expand in detail based on the brief component description provided by the user./g' "$FILE"
sed -i '' 's/原始组件名称/Original Component Name/g' "$FILE"
sed -i '' 's/原始描述/Original Description/g' "$FILE"
sed -i '' 's/请将这个描述扩写为更详细、更专业的产品需求描述，包括：/Please expand this description into a more detailed, professional product requirements description, including:/g' "$FILE"
sed -i '' 's/组件的核心功能和用途/Core functions and purpose of the component/g' "$FILE"
sed -i '' 's/用户交互方式和行为/User interaction methods and behaviors/g' "$FILE"
sed -i '' 's/视觉呈现和布局要求/Visual presentation and layout requirements/g' "$FILE"
sed -i '' 's/数据展示和处理方式/Data display and processing methods/g' "$FILE"
sed -i '' 's/边界情况和错误处理/Edge cases and error handling/g' "$FILE"
sed -i '' 's/要求/Requirements/g' "$FILE"
sed -i '' 's/保持简洁明了，不要过于冗长/Keep it concise and clear, not too verbose/g' "$FILE"
sed -i '' 's/使用产品需求的语言风格/Use product requirements language style/g' "$FILE"
sed -i '' 's/突出关键功能和特性/Highlight key functions and features/g' "$FILE"
sed -i '' 's/控制在 200-300 字以内/Keep within 200-300 words/g' "$FILE"
sed -i '' 's/直接输出扩写后的描述，不要有其他解释/Directly output the expanded description, no other explanation/g' "$FILE"
sed -i '' 's/扩写后的描述/Expanded description/g' "$FILE"

# Architecture analysis
sed -i '' 's/# 组件架构分析任务/# Component Architecture Analysis Task/g' "$FILE"
sed -i '' 's/请深入分析以下组件需求，设计合理的\*\*多文件组件架构\*\*。/Please deeply analyze the following component requirements and design a reasonable \*\*multi-file component architecture\*\*./g' "$FILE"
sed -i '' 's/组件信息/Component Information/g' "$FILE"
sed -i '' 's/通用组件/Generic Component/g' "$FILE"
sed -i '' 's/描述/Description/g' "$FILE"
sed -i '' 's/本项目固定使用多文件组件化方案/This project uses a fixed multi-file componentization approach/g' "$FILE"
sed -i '' 's/无论组件简单或复杂，都必须拆分为多个文件。/Regardless of whether the component is simple or complex, it must be split into multiple files./g' "$FILE"
sed -i '' 's/最小文件结构（至少 2 个文件）/Minimum file structure (at least 2 files)/g' "$FILE"
sed -i '' 's/主组件/Main Component/g' "$FILE"
sed -i '' 's/内容子组件/Content Sub-Component/g' "$FILE"
sed -i '' 's/推荐的多文件结构/Recommended multi-file structure/g' "$FILE"
sed -i '' 's/头部子组件/Header Sub-Component/g' "$FILE"
sed -i '' 's/主体子组件/Body Sub-Component/g' "$FILE"
sed -i '' 's/底部子组件/Footer Sub-Component/g' "$FILE"
sed -i '' 's/工具函数，可选/Utility functions, optional/g' "$FILE"
sed -i '' 's/输出格式（严格 JSON）/Output Format (Strict JSON)/g' "$FILE"
sed -i '' 's/简洁的组件描述/Concise component description/g' "$FILE"
sed -i '' 's/组件头部区域，展示标题和主要操作/Component header area, displays title and main actions/g' "$FILE"
sed -i '' 's/组件主要内容区域/Component main content area/g' "$FILE"
sed -i '' 's/格式化数据用于展示/Format data for display/g' "$FILE"
sed -i '' 's/关键要求/Key Requirements/g' "$FILE"
sed -i '' 's/必须拆分至少 1 个子组件/Must split at least 1 sub-component/g' "$FILE"
sed -i '' 's/即使是很简单的组件，也要拆出内容部分/Even for very simple components, separate the content part/g' "$FILE"
sed -i '' 's/主组件负责状态管理，子组件负责 UI 渲染/Main component handles state management, sub-component handles UI rendering/g' "$FILE"
sed -i '' 's/子组件拆分原则/Sub-component splitting principles/g' "$FILE"
sed -i '' 's/每个子组件职责单一，遵循单一职责原则/Each sub-component has a single responsibility, following the single responsibility principle/g' "$FILE"
sed -i '' 's/子组件之间低耦合，高内聚/Sub-components are loosely coupled and highly cohesive/g' "$FILE"
sed -i '' 's/避免过度拆分（不超过 6 个子组件）/Avoid over-splitting (no more than 6 sub-components)/g' "$FILE"
sed -i '' 's/子组件代码行数控制在 40-80 行/Sub-component code lines controlled to 40-80 lines/g' "$FILE"
sed -i '' 's/工具函数提取原则/Utility function extraction principles/g' "$FILE"
sed -i '' 's/纯函数，无副作用/Pure functions, no side effects/g' "$FILE"
sed -i '' 's/可复用性强/High reusability/g' "$FILE"
sed -i '' 's/放在 utils\/ 目录/Place in utils\/ directory/g' "$FILE"
sed -i '' 's/每个文件不超过 30 行/Each file does not exceed 30 lines/g' "$FILE"
sed -i '' 's/命名规范/Naming conventions/g' "$FILE"
sed -i '' 's/组件名使用 PascalCase/Component names use PascalCase/g' "$FILE"
sed -i '' 's/文件路径使用 kebab-case 或 camelCase/File paths use kebab-case or camelCase/g' "$FILE"
sed -i '' 's/工具函数使用 camelCase/Utility functions use camelCase/g' "$FILE"
sed -i '' 's/依赖关系/Dependencies/g' "$FILE"
sed -i '' 's/主组件依赖所有子组件/Main component depends on all sub-components/g' "$FILE"
sed -i '' 's/子组件可以依赖工具函数/Sub-components can depend on utility functions/g' "$FILE"
sed -i '' 's/避免循环依赖/Avoid circular dependencies/g' "$FILE"
sed -i '' 's/输出要求/Output Requirements/g' "$FILE"
sed -i '' 's/只输出 JSON/Output only JSON/g' "$FILE"
sed -i '' 's/不要包含 Markdown 代码块标记/Do not include Markdown code block markers/g' "$FILE"
sed -i '' 's/不要添加任何解释性文字/Do not add any explanatory text/g' "$FILE"
sed -i '' 's/确保 JSON 格式正确/Ensure JSON format is correct/g' "$FILE"
sed -i '' 's/可以被 JSON.parse\(\) 解析/Can be parsed by JSON.parse()/g' "$FILE"
sed -i '' 's/必须准确反映总行数/Must accurately reflect total lines/g' "$FILE"

echo "Comprehensive replacement completed!"
